name: CI on Push and Pull Request

on: [push]

jobs:        
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        cd HingeIt
        nuget restore
        cd HingeIt.Android
        msbuild HingeIt.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug

